#!/usr/bin/env python3
"""Generate frontend/index.html for THEMIS."""
import pathlib

out = pathlib.Path("frontend/index.html").open("w", encoding="utf-8")

def w(s=""):
    out.write(s + "\n")

w("<!DOCTYPE html>")
w('<html lang="en">')
w("<head>")
w('  <meta charset="UTF-8" />')
w('  <meta name="viewport" content="width=device-width, initial-scale=1.0" />')
w("  <title>Aition - Causal AI Fairness Engine</title>")
w('  <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>')
w('  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>')
w('  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>')
w("  <style>")
w("    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }")
w("    body { font-family: system-ui, -apple-system, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; padding: 2rem; }")
w("    header { text-align: center; margin-bottom: 2rem; }")
w("    header h1 { font-size: 2.5rem; font-weight: 800; color: #7C3AED; letter-spacing: -0.02em; }")
w("    header .subtitle { color: #94a3b8; margin-top: 0.5rem; font-size: 1rem; }")
w("    header .tagline { font-size: 0.85rem; color: #64748b; font-style: italic; margin-top: 0.4rem; max-width: 680px; margin-left: auto; margin-right: auto; }")
w("    #controls { display: flex; gap: 1rem; justify-content: center; align-items: center; flex-wrap: wrap; margin-bottom: 1.5rem; }")
w("    #btn-demo { background: #7C3AED; color: #fff; border: none; padding: 0.75rem 1.75rem; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: background 0.2s; }")
w("    #btn-demo:hover { background: #6d28d9; }")
w("    #file-label { background: #1e293b; border: 1px solid #334155; color: #94a3b8; padding: 0.75rem 1.25rem; border-radius: 8px; font-size: 0.9rem; cursor: pointer; transition: border-color 0.2s; }")
w("    #file-label:hover { border-color: #7C3AED; }")
w("    #csv-input { display: none; }")
w("    #loading { display: none; text-align: center; padding: 2rem; color: #94a3b8; font-size: 1.1rem; }")
w("    #loading span { animation: pulse-text 1.2s ease-in-out infinite; }")
w("    @keyframes pulse-text { 0%,100% { opacity:1 } 50% { opacity:0.4 } }")
w("    #error-box { display: none; background: #450a0a; border: 1px solid #DC2626; border-radius: 8px; padding: 1rem 1.5rem; color: #fca5a5; margin-bottom: 1.5rem; max-width: 700px; margin-left: auto; margin-right: auto; }")
w("    #results { display: none; }")
w("    .panels { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem; }")
w("    @media (max-width: 700px) { .panels { grid-template-columns: 1fr; } }")
w("    .panel { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; }")
w("    .panel h2 { font-size: 1rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1rem; }")
w("    .badge { display: inline-block; padding: 0.5rem 1.25rem; border-radius: 6px; font-size: 1.1rem; font-weight: 700; margin-bottom: 1rem; }")
w("    .badge-fair { background: #14532d; color: #86efac; }")
w("    .badge-biased { background: #450a0a; color: #fca5a5; }")
w("    .badge-proxy { background: #450a0a; color: #fca5a5; }")
w("    .badge-no-proxy { background: #14532d; color: #86efac; }")
w("    .badge-bias-green { background: #14532d; color: #86efac; }")
w("    .badge-bias-amber { background: #451a03; color: #fcd34d; }")
w("    .badge-bias-red { background: #450a0a; color: #fca5a5; }")
w("    .metric-label { color: #94a3b8; font-size: 0.85rem; margin-bottom: 0.25rem; }")
w("    .metric-value { font-size: 1.4rem; font-weight: 700; color: #e2e8f0; margin-bottom: 1rem; }")

w("    .proxy-list { list-style: none; margin-top: 0.5rem; }")
w("    .proxy-list li { background: #0f172a; border: 1px solid #334155; border-radius: 6px; padding: 0.6rem 0.9rem; margin-bottom: 0.5rem; font-size: 0.85rem; color: #cbd5e1; }")
w("    .proxy-list li strong { color: #f87171; }")
w("    .affected-count { margin-top: 1rem; background: #1c1917; border: 1px solid #DC2626; border-radius: 6px; padding: 0.75rem 1rem; color: #fca5a5; font-size: 0.9rem; }")
w("    .affected-count strong { font-size: 1.2rem; color: #f87171; }")
w("    #graph-section { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }")
w("    #graph-section h2 { font-size: 1rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1rem; }")
w("    #graph-svg { width: 100%; height: 520px; display: block; }")
w("    #impossibility-section { display: none; background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }")
w("    #impossibility-section h2 { font-size: 1rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.25rem; }")
w("    #impossibility-section .subtitle { color: #64748b; font-size: 0.85rem; margin-bottom: 1.25rem; font-style: italic; }")
w("    .slider-labels { display: flex; justify-content: space-between; font-size: 0.85rem; color: #94a3b8; margin-bottom: 0.5rem; }")
w("    #impossibility-slider { width: 100%; accent-color: #7C3AED; cursor: pointer; margin-bottom: 1.25rem; }")
w("    .metric-row { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.6rem; }")
w("    .metric-row .metric-name { width: 160px; font-size: 0.85rem; color: #94a3b8; flex-shrink: 0; }")
w("    .metric-bar-wrap { flex: 1; background: #0f172a; border-radius: 4px; height: 8px; overflow: hidden; }")
w("    .metric-bar { height: 100%; border-radius: 4px; transition: width 0.2s ease; }")
w("    .bar-dp { background: #7C3AED; }")
w("    .bar-eo { background: #0ea5e9; }")
w("    .bar-acc { background: #16A34A; }")
w("    .metric-row .metric-num { width: 60px; text-align: right; font-size: 0.85rem; font-weight: 600; color: #e2e8f0; }")
w("    #slider-explanation { font-size: 0.85rem; color: #64748b; margin: 0.75rem 0 1.25rem; font-style: italic; }")
w("    #btn-confirm-debias { background: #7C3AED; color: #fff; border: none; padding: 0.65rem 1.5rem; border-radius: 8px; font-size: 0.95rem; font-weight: 600; cursor: pointer; transition: background 0.2s; }")
w("    #btn-confirm-debias:hover:not(:disabled) { background: #6d28d9; }")
w("    #btn-confirm-debias:disabled { opacity: 0.6; cursor: not-allowed; }")
w("    #debiasing-section { display: none; background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }")
w("    #debiasing-section h2 { font-size: 1rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1.25rem; }")
w("    .debias-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1rem; }")
w("    @media (max-width: 600px) { .debias-columns { grid-template-columns: 1fr; } }")
w("    .debias-col { background: #0f172a; border: 1px solid #334155; border-radius: 8px; padding: 1rem; }")
w("    .debias-col-label { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 0.75rem; }")
w("    .debias-bias-value { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }")
w("    .debias-bias-before { color: #f87171; }")
w("    .debias-bias-after { color: #4ade80; }")
w("    .debias-bar-wrap { background: #1e293b; border-radius: 4px; height: 10px; overflow: hidden; margin-bottom: 0.75rem; }")
w("    .debias-bar { height: 100%; border-radius: 4px; transition: width 1s ease; }")
w("    .debias-bar-before { background: #DC2626; }")
w("    .debias-bar-after { background: #16A34A; }")
w("    .debias-accuracy { font-size: 0.9rem; color: #94a3b8; }")
w("    .debias-accuracy span { color: #e2e8f0; font-weight: 600; }")
w("    .debias-modified { margin-bottom: 1rem; }")
w("    .debias-modified-item { display: flex; align-items: center; gap: 0.5rem; font-size: 0.85rem; color: #cbd5e1; padding: 0.4rem 0; border-bottom: 1px solid #1e293b; }")
w("    .debias-modified-item:last-child { border-bottom: none; }")
w("    .debias-scissors { color: #a78bfa; font-size: 1rem; }")
w("    .debias-summary { background: #0f172a; border: 1px solid #334155; border-radius: 8px; padding: 0.75rem 1rem; display: flex; gap: 1.5rem; flex-wrap: wrap; font-size: 0.85rem; }")
w("    .debias-summary-item { color: #94a3b8; }")
w("    .debias-summary-item .cost-val { font-weight: 700; color: #fbbf24; }")
w("    .debias-summary-item .benefit-val { font-weight: 700; color: #4ade80; }")
w("    #report-section { display: none; background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }")
w("    #report-section h2 { font-size: 1rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1rem; }")
w("    #report-text { font-size: 0.92rem; line-height: 1.8; color: #cbd5e1; }")
w("    #report-text h1, #report-text h2, #report-text h3 { color: #e2e8f0; margin: 1.2rem 0 0.5rem; font-weight: 700; }")
w("    #report-text h1 { font-size: 1.4rem; }")
w("    #report-text h2 { font-size: 1.15rem; border-bottom: 1px solid #334155; padding-bottom: 0.3rem; }")
w("    #report-text h3 { font-size: 1rem; color: #a78bfa; }")
w("    #report-text p { margin-bottom: 0.75rem; }")
w("    #report-text ul, #report-text ol { padding-left: 1.5rem; margin-bottom: 0.75rem; }")
w("    #report-text li { margin-bottom: 0.3rem; }")
w("    #report-text strong { color: #f1f5f9; }")
w("    #report-text hr { border-color: #334155; margin: 1rem 0; }")
w("    #report-text code { background: #0f172a; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.85em; }")
w("    #btn-download-pdf { background: #1e293b; border: 1px solid #7C3AED; color: #a78bfa; padding: 0.5rem 1.25rem; border-radius: 6px; font-size: 0.85rem; font-weight: 600; cursor: pointer; transition: background 0.2s; margin-bottom: 1rem; display: inline-block; }")
w("    #btn-download-pdf:hover { background: #2d1f5e; }")
w("    #tooltip { position: fixed; background: #1e293b; border: 1px solid #475569; border-radius: 6px; padding: 0.5rem 0.75rem; font-size: 0.8rem; color: #e2e8f0; pointer-events: none; display: none; z-index: 100; max-width: 220px; }")
w("    @keyframes pulse { 0%,100% { opacity:1 } 50% { opacity:0.4 } }")
w("    .proxy-edge { animation: pulse 1.8s ease-in-out infinite; }")
w("  </style>")
w("</head>")
w("<body>")


# ── BODY ──────────────────────────────────────────────────────────
w('<header>')
w('  <h1>Aition</h1>')
w('  <p class="subtitle">Causal AI Fairness Engine</p>')
w('  <p class="tagline">The only system that finds AI discrimination that passes every standard fairness test — because it thinks causally, not statistically.</p>')
w('</header>')
w('<div id="controls">')
w('  <button id="btn-demo">Use Demo Dataset</button>')
w('  <label id="file-label" for="csv-input">Upload CSV</label>')
w('  <input type="file" id="csv-input" accept=".csv" />')
w('</div>')
w('<div id="error-box"></div>')
w('<div id="loading"><span>Running causal audit...</span></div>')
w('<div id="results">')
w('  <div class="panels">')
w('    <div class="panel" id="standard-panel">')
w('      <h2>Standard Audit (AIF360)</h2>')
w('      <div id="std-badge"></div>')
w('      <div class="metric-label">Demographic Parity Difference</div>')
w('      <div class="metric-value" id="std-dpd"></div>')
w('      <div class="metric-label">Bias Index</div>')
w('      <div id="bias-index-badge"></div>')
w('    </div>')
w('    <div class="panel" id="causal-panel">')
w('      <h2>Causal Audit (DoWhy)</h2>')
w('      <div id="causal-badge"></div>')
w('      <div class="metric-label">Proxy Paths Found</div>')
w('      <div class="metric-value" id="causal-paths"></div>')
w('      <ul class="proxy-list" id="proxy-list"></ul>')
w('      <div class="affected-count" id="affected-count"></div>')
w('    </div>')
w('  </div>')
w('  <div id="graph-section">')
w('    <h2>Causal Graph</h2>')
w('    <svg id="graph-svg"></svg>')
w('  </div>')
w('  <!-- Layer 2: Impossibility Slider -->')
w('  <div id="impossibility-section">')
w('    <h2>Fairness Definition Selector</h2>')
w('    <p class="subtitle">These three definitions of fairness are mathematically incompatible. (Chouldechova 2017)</p>')
w('    <div class="slider-labels"><span>Demographic Parity</span><span>Equalized Odds</span></div>')
w('    <input type="range" id="impossibility-slider" min="0" max="100" value="0" />')
w('    <div class="metric-row">')
w('      <span class="metric-name">Demographic Parity</span>')
w('      <div class="metric-bar-wrap"><div class="metric-bar bar-dp" id="dp-bar" style="width:50%"></div></div>')
w('      <span class="metric-num" id="dp-value">—</span>')
w('    </div>')
w('    <div class="metric-row">')
w('      <span class="metric-name">Equalized Odds</span>')
w('      <div class="metric-bar-wrap"><div class="metric-bar bar-eo" id="eo-bar" style="width:50%"></div></div>')
w('      <span class="metric-num" id="eo-value">—</span>')
w('    </div>')
w('    <div class="metric-row">')
w('      <span class="metric-name">Model Accuracy</span>')
w('      <div class="metric-bar-wrap"><div class="metric-bar bar-acc" id="acc-bar" style="width:90%"></div></div>')
w('      <span class="metric-num" id="accuracy-value">—</span>')
w('    </div>')
w('    <p id="slider-explanation"></p>')
w('    <button id="btn-confirm-debias">Confirm: Apply Demographic Parity →</button>')
w('  </div>')
w('  <!-- Layer 3: Debiasing Result -->')
w('  <div id="debiasing-section">')
w('    <h2>Surgical Debiasing Complete</h2>')
w('    <div class="debias-columns">')
w('      <div class="debias-col">')
w('        <div class="debias-col-label">Before</div>')
w('        <div class="debias-bias-value debias-bias-before" id="bias-before-val">—</div>')
w('        <div class="debias-bar-wrap"><div class="debias-bar debias-bar-before" id="bias-before-bar" style="width:0%"></div></div>')
w('        <div class="debias-accuracy">Accuracy: <span id="acc-before-val">—</span></div>')
w('      </div>')
w('      <div class="debias-col">')
w('        <div class="debias-col-label">After</div>')
w('        <div class="debias-bias-value debias-bias-after" id="bias-after-val">—</div>')
w('        <div class="debias-bar-wrap"><div class="debias-bar debias-bar-after" id="bias-after-bar" style="width:0%"></div></div>')
w('        <div class="debias-accuracy">Accuracy: <span id="acc-after-val">—</span></div>')
w('      </div>')
w('    </div>')
w('    <div class="debias-modified" id="debias-modified-list"></div>')
w('    <div class="debias-summary">')
w('      <div class="debias-summary-item">Accuracy cost: <span class="cost-val" id="debias-cost">—</span></div>')
w('      <div class="debias-summary-item">Bias reduction: <span class="benefit-val" id="debias-benefit">—</span></div>')
w('    </div>')
w('  </div>')
w('  <!-- Layer 4: Report -->')
w('  <div id="report-section">')
w('    <h2>Plain-Language Report</h2>')
w('    <button id="btn-download-pdf">Download as PDF</button>')
w('    <div id="report-text"></div>')
w('  </div>')
w('</div>')
w('<div id="tooltip"></div>')

# ── JAVASCRIPT ────────────────────────────────────────────────────
w('<script>')
w('let auditId = null;')
w('let selectedDefinition = "demographic_parity";')
w('')
w('// ── Utility ──────────────────────────────────────────────────')
w('function showError(msg) {')
w('  const b = document.getElementById("error-box");')
w('  b.textContent = msg; b.style.display = "block";')
w('}')
w('function hideError() { document.getElementById("error-box").style.display = "none"; }')
w('function biasIndexClass(v) {')
w('  if (v < 0.2) return "badge-bias-green";')
w('  if (v < 0.5) return "badge-bias-amber";')
w('  return "badge-bias-red";')
w('}')
w('')
w('// ── Run Audit ────────────────────────────────────────────────')
w('async function runAudit(file) {')
w('  hideError();')
w('  document.getElementById("results").style.display = "none";')
w('  document.getElementById("impossibility-section").style.display = "none";')
w('  document.getElementById("debiasing-section").style.display = "none";')
w('  document.getElementById("report-section").style.display = "none";')
w('  document.getElementById("loading").style.display = "block";')
w('  try {')
w('    const fd = new FormData();')
w('    if (file) fd.append("file", file);')
w('    const res = await fetch("http://localhost:8000/audit", { method: "POST", body: fd });')
w('    if (!res.ok) { const e = await res.json(); throw new Error(`HTTP ${res.status}: ${e.detail || e.error}`); }')
w('    const data = await res.json();')
w('    auditId = data.audit_id;')
w('    renderResults(data);')
w('  } catch(e) { showError(e.message); }')
w('  finally { document.getElementById("loading").style.display = "none"; }')
w('}')
w('')
w('// ── Render Results ───────────────────────────────────────────')
w('function renderResults(data) {')
w('  const s = data.standard_audit;')
w('  const c = data.causal_audit;')
w('  // Standard panel')
w('  document.getElementById("std-badge").innerHTML = `<span class="badge ${s.passes_standard_test ? "badge-fair" : "badge-biased"}">${s.verdict} ${s.passes_standard_test ? "✓" : "✗"}</span>`;')
w('  document.getElementById("std-dpd").textContent = s.demographic_parity_difference.toFixed(4);')
w('  const bi = data.bias_index;')
w('  document.getElementById("bias-index-badge").innerHTML = `<span class="badge ${biasIndexClass(bi)}">Bias Index: ${bi.toFixed(4)}</span>`;')
w('  // Causal panel')
w('  document.getElementById("causal-badge").innerHTML = `<span class="badge ${c.proxy_paths_found > 0 ? "badge-proxy" : "badge-no-proxy"}">${c.verdict}</span>`;')
w('  document.getElementById("causal-paths").textContent = c.proxy_paths_found;')
w('  const pl = document.getElementById("proxy-list"); pl.innerHTML = "";')
w('  c.paths.forEach(p => {')
w('    const li = document.createElement("li");')
w('    li.innerHTML = `<strong>${p.path.join(" → ")}</strong> — effect: ${p.effect.toFixed(3)}`;')
w('    pl.appendChild(li);')
w('  });')
w('  document.getElementById("affected-count").innerHTML = `<strong>${c.affected_candidates}</strong> candidates affected by proxy discrimination`;')
w('  // Graph')
w('  renderGraph(data.graph_data);')
w('  // Report')
w('  document.getElementById("report-text").innerHTML = marked.parse(data.plain_language_report || "");')
w('  document.getElementById("report-section").style.display = "block";')
w('  document.getElementById("results").style.display = "block";')
w('  // Impossibility slider')
w('  if (data.impossibility_surface) initImpossibilitySlider(data.impossibility_surface);')
w('}')
w('')
w('// ── Impossibility Slider ─────────────────────────────────────')
w('function initImpossibilitySlider(surface) {')
w('  const slider = document.getElementById("impossibility-slider");')
w('  const points = surface.frontier_points;')
w('  const accuracies = surface.accuracy_at_threshold;')
w('  const maxDP = Math.max(...points.map(p => p[0])) || 0.3;')
w('  const maxEO = Math.max(...points.map(p => p[1])) || 0.3;')
w('  function update() {')
w('    const idx = Math.round(slider.value * (points.length - 1) / 100);')
w('    const [dpd, eod] = points[idx];')
w('    const acc = accuracies[idx];')
w('    document.getElementById("dp-value").textContent = dpd.toFixed(3);')
w('    document.getElementById("eo-value").textContent = eod.toFixed(3);')
w('    document.getElementById("accuracy-value").textContent = (acc * 100).toFixed(1) + "%";')
w('    document.getElementById("dp-bar").style.width = Math.min(100, (dpd / maxDP) * 100) + "%";')
w('    document.getElementById("eo-bar").style.width = Math.min(100, (eod / maxEO) * 100) + "%";')
w('    document.getElementById("acc-bar").style.width = (acc * 100) + "%";')
w('    const cost = ((accuracies[0] - acc) * 100).toFixed(1);')
w('    const pos = slider.value > 50 ? "Equalized Odds" : "Demographic Parity";')
w('    selectedDefinition = slider.value > 50 ? "equalized_odds" : "demographic_parity";')
w('    document.getElementById("btn-confirm-debias").textContent = `Confirm: Apply ${pos} →`;')
w('    document.getElementById("slider-explanation").textContent =')
w('      `Moving toward Equalized Odds costs ${cost}% accuracy but reduces error rate disparity.`;')
w('  }')
w('  slider.addEventListener("input", update);')
w('  update();')
w('  document.getElementById("impossibility-section").style.display = "block";')
w('}')
w('')
w('// ── Run Debiasing ────────────────────────────────────────────')
w('async function runDebiasing(definition) {')
w('  const btn = document.getElementById("btn-confirm-debias");')
w('  btn.disabled = true;')
w('  btn.textContent = "Running debiasing...";')
w('  try {')
w('    const res = await fetch(`http://localhost:8000/audit/${auditId}/debias`, {')
w('      method: "POST",')
w('      headers: { "Content-Type": "application/json" },')
w('      body: JSON.stringify({ selected_fairness_definition: definition })')
w('    });')
w('    if (!res.ok) { const e = await res.json(); throw new Error(`HTTP ${res.status}: ${e.detail || e.error}`); }')
w('    const data = await res.json();')
w('    renderDebiasingResult(data);')
w('  } catch(e) {')
w('    showError("Debiasing failed: " + e.message);')
w('    btn.disabled = false;')
w('    btn.textContent = `Confirm: Apply ${definition.replace("_", " ")} →`;')
w('  }')
w('}')
w('')
w('// ── Render Debiasing Result ───────────────────────────────────')
w('function renderDebiasingResult(result) {')
w('  document.getElementById("bias-before-val").textContent = result.bias_index_before.toFixed(4);')
w('  document.getElementById("bias-after-val").textContent = result.bias_index_after.toFixed(4);')
w('  document.getElementById("acc-before-val").textContent = (result.accuracy_before * 100).toFixed(1) + "%";')
w('  document.getElementById("acc-after-val").textContent = (result.accuracy_after * 100).toFixed(1) + "%";')
w('  document.getElementById("debias-cost").textContent = result.accuracy_cost_percent.toFixed(1) + "%";')
w('  document.getElementById("debias-benefit").textContent = result.bias_reduction_percent.toFixed(1) + "% ↓";')
w('  // Animate bars (start at 0, then transition to real values)')
w('  const beforeBar = document.getElementById("bias-before-bar");')
w('  const afterBar = document.getElementById("bias-after-bar");')
w('  beforeBar.style.width = "0%"; afterBar.style.width = "0%";')
w('  setTimeout(() => {')
w('    beforeBar.style.width = Math.min(100, result.bias_index_before * 100) + "%";')
w('    afterBar.style.width = Math.min(100, result.bias_index_after * 100) + "%";')
w('  }, 50);')
w('  // Variables modified list')
w('  const modList = document.getElementById("debias-modified-list");')
w('  modList.innerHTML = result.variables_modified.map(v =>')
w('    `<div class="debias-modified-item"><span class="debias-scissors">✂</span> ${v}</div>`')
w('  ).join("");')
w('  document.getElementById("debiasing-section").style.display = "block";')
w('  document.getElementById("debiasing-section").scrollIntoView({ behavior: "smooth" });')
w('}')
w('')
w('// ── Causal Graph (D3) ────────────────────────────────────────')
w('function renderGraph(gd) {')
w('  const svg = d3.select("#graph-svg");')
w('  svg.selectAll("*").remove();')
w('  const W = document.getElementById("graph-svg").clientWidth || 900;')
w('  const H = 520;')
w('  const nodeColor = { protected: "#7C3AED", proxy: "#DC2626", legitimate: "#16A34A", outcome: "#6B7280" };')
w('  const pos = {')
w('    gender:           [W * 0.12, H * 0.5],')
w('    college_tier:     [W * 0.38, H * 0.25],')
w('    employment_gap:   [W * 0.38, H * 0.75],')
w('    test_score:       [W * 0.62, H * 0.25],')
w('    experience_years: [W * 0.62, H * 0.75],')
w('    hired:            [W * 0.88, H * 0.5]')
w('  };')
w('  // Defs: glow filter + arrowheads')
w('  const defs = svg.append("defs");')
w('  const glow = defs.append("filter").attr("id","glow");')
w('  glow.append("feGaussianBlur").attr("stdDeviation","3").attr("result","blur");')
w('  const merge = glow.append("feMerge");')
w('  merge.append("feMergeNode").attr("in","blur");')
w('  merge.append("feMergeNode").attr("in","SourceGraphic");')
w('  ["proxy","legit"].forEach(t => {')
w('    defs.append("marker").attr("id","arrow-"+t).attr("viewBox","0 -5 10 10")')
w('      .attr("refX",28).attr("refY",0).attr("markerWidth",6).attr("markerHeight",6)')
w('      .attr("orient","auto")')
w('      .append("path").attr("d","M0,-5L10,0L0,5")')
w('      .attr("fill", t === "proxy" ? "#DC2626" : "#16A34A");')
w('  });')
w('  // Edges')
w('  const edgeG = svg.append("g").attr("opacity",0);')
w('  gd.edges.forEach(e => {')
w('    const [x1,y1] = pos[e.source]; const [x2,y2] = pos[e.target];')
w('    const isProxy = e.type === "proxy";')
w('    const line = edgeG.append("line")')
w('      .attr("x1",x1).attr("y1",y1).attr("x2",x2).attr("y2",y2)')
w('      .attr("stroke", isProxy ? "#DC2626" : "#16A34A")')
w('      .attr("stroke-width", isProxy ? 4 : 2.5)')
w('      .attr("marker-end", "url(#arrow-" + (isProxy ? "proxy" : "legit") + ")")')
w('      .attr("filter", isProxy ? "url(#glow)" : null);')
w('    if (isProxy) line.classed("proxy-edge", true);')
w('    // Strength label')
w('    const mx = (x1+x2)/2; const my = (y1+y2)/2;')
w('    edgeG.append("rect").attr("x",mx-18).attr("y",my-10).attr("width",36).attr("height",18)')
w('      .attr("rx",9).attr("fill","#1e293b").attr("stroke", isProxy ? "#DC2626" : "#16A34A").attr("stroke-width",1);')
w('    edgeG.append("text").attr("x",mx).attr("y",my+4).attr("text-anchor","middle")')
w('      .attr("font-size","10").attr("fill", isProxy ? "#f87171" : "#86efac")')
w('      .text(e.strength.toFixed(2));')
w('  });')
w('  // Nodes')
w('  const nodeG = svg.append("g").attr("opacity",0);')
w('  const tooltip = document.getElementById("tooltip");')
w('  const roleDesc = { protected:"Protected attribute", proxy:"Proxy variable (bias path)", legitimate:"Legitimate feature", outcome:"Outcome variable" };')
w('  gd.nodes.forEach(n => {')
w('    const [x,y] = pos[n.id] || [W/2, H/2];')
w('    const g = nodeG.append("g").attr("transform",`translate(${x},${y})`).style("cursor","pointer");')
w('    g.append("circle").attr("r",26).attr("fill", nodeColor[n.type] || "#6B7280").attr("stroke","#0f172a").attr("stroke-width",2);')
w('    g.append("text").attr("text-anchor","middle").attr("dy","0.35em").attr("font-size","10")')
w('      .attr("fill","#fff").attr("font-weight","600").text(n.label.replace("_"," "));')
w('    g.on("mouseover", (ev) => {')
w('      tooltip.style.display = "block";')
w('      tooltip.innerHTML = `<strong>${n.label}</strong><br/>${n.type} — ${roleDesc[n.type] || ""}`;')
w('    }).on("mousemove", (ev) => {')
w('      tooltip.style.left = (ev.clientX + 12) + "px";')
w('      tooltip.style.top  = (ev.clientY - 28) + "px";')
w('    }).on("mouseout", () => { tooltip.style.display = "none"; });')
w('  });')
w('  // Legend')
w('  const legendData = [')
w('    { label:"Protected", color:"#7C3AED" }, { label:"Proxy", color:"#DC2626" },')
w('    { label:"Legitimate", color:"#16A34A" }, { label:"Outcome", color:"#6B7280" }')
w('  ];')
w('  const leg = svg.append("g").attr("transform",`translate(16,${H-60})`);')
w('  legendData.forEach((d,i) => {')
w('    leg.append("circle").attr("cx",i*110).attr("cy",0).attr("r",7).attr("fill",d.color);')
w('    leg.append("text").attr("x",i*110+12).attr("y",4).attr("font-size","11").attr("fill","#94a3b8").text(d.label);')
w('  });')
w('  // Animate: nodes first, then edges')
w('  nodeG.transition().duration(600).attr("opacity",1);')
w('  edgeG.transition().delay(600).duration(800).attr("opacity",1);')
w('}')
w('')
w('// ── Event Listeners ──────────────────────────────────────────')
w('document.getElementById("btn-demo").addEventListener("click", () => runAudit(null));')
w('document.getElementById("csv-input").addEventListener("change", e => {')
w('  if (e.target.files[0]) runAudit(e.target.files[0]);')
w('});')
w('document.getElementById("btn-confirm-debias").addEventListener("click", () => {')
w('  runDebiasing(selectedDefinition);')
w('});')
w('document.getElementById("btn-download-pdf").addEventListener("click", () => {')
w('  html2pdf().set({ margin:10, filename:"themis-report.pdf", html2canvas:{scale:2}, jsPDF:{unit:"mm",format:"a4"} })')
w('    .from(document.getElementById("report-text")).save();')
w('});')
w('</script>')
w('</body>')
w('</html>')
out.close()
print("Done — frontend/index.html written.")
